#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Trinity
echo "${y}*******************"
echo 'Trinity'
echo "*******************${w}"
trinity_path=/node_temp/trinityrnaseq-v2.14.0
trinity_tar=trinityrnaseq-v2.14.0.FULL.tar.gz
trinity_tar_URL=https://github.com/trinityrnaseq/trinityrnaseq/releases/download/Trinity-v2.14.0/trinityrnaseq-v2.14.0.FULL.tar.gz

#remove old version
ssh $node_name "rm -rf /usr/local/bin/trinityrnaseq*"
ssh $node_name "su -c 'cd /node_temp/ && wget $trinity_tar_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $trinity_tar' $user_name"
ssh $node_name "su -c 'cd $trinity_path && make -j $threads' $user_name"
ssh $node_name "cd $trinity_path && sudo make install -j $threads"
ssh $node_name "rm -rf $trinity_path /node_temp/$trinity_tar"
#ssh $node_name "ln -fs /usr/local/bin/python3 /usr/local/bin/python"
ssh $node_name "sudo ln -s /usr/bin/python3 /usr/bin/python"



ssh $node_name "cp -f /usr/local/bin/ParaFly /usr/local/bin/trinity-plugins/BIN/ParaFly"
trinity_version=`ssh $node_name /usr/local/bin/Trinity --version`

ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "--------------------------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------------------------${y}"
echo    "$trinity_version"
echo    "${g}---------------------------------------------------------------------"
