#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#HTSLIB
echo "${y}*******************"
echo 'htslib'
echo "*******************${w}"
HTSLIB_tar=/node_temp/htslib-1.11.tar.bz2
HTSLIB_path=/node_temp/htslib-1.11/
HTS_LIB_URL=https://github.com/samtools/htslib/releases/download/1.11/htslib-1.11.tar.bz2
ssh $node_name "sudo apt-fast -y install autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev"
ssh $node_name "su -c 'cd /node_temp/ && wget $HTS_LIB_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar xjf $HTSLIB_tar' $user_name"
ssh $node_name "su -c 'cd $HTSLIB_path && ./configure' $user_name"
ssh $node_name "su -c 'cd $HTSLIB_path && make -j $threads' $user_name"
ssh $node_name "cd $HTSLIB_path && make install -j $threads"
echo "${g}"
echo    "---------------------------------"
echo	"Hostname=${w}$node_name         " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------${y}"
basename $HTSLIB_path
ssh $node_name "rm -rf $HTSLIB_path $HTSLIB_tar"
ssh $node_name 'rm -rf /node_temp/'
echo    "${g}-----------------------------"
