#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#SAMTOOLS
echo "${y}*******************"
echo 'samtools'
echo "*******************${w}"
samtools_path=/node_temp/samtools-1.11/
samtools_bz2=/node_temp/samtools-1.11.tar.bz2
samtools_URL=https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2
ssh $node_name "apt-get install libcurl3 -y"
ssh $node_name "su -c 'cd /node_temp/ && wget $samtools_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar xjf $samtools_bz2' $user_name"
ssh $node_name "su -c 'cd $samtools_path && ./configure' $user_name"
ssh $node_name "su -c 'cd $samtools_path && make -j $threads' $user_name"
ssh $node_name "cd $samtools_path && make install -j $threads"
ssh $node_name "rm -rf $samtools_path $samtools_bz2"
samtools_v=`ssh $node_name samtools --version | grep samtools`


ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "---------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------${y}"
echo    "$samtools_v"
echo    "${g}---------------------------------------------"
