#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#BCFtools
echo "${y}*******************"
echo 'BCFtools'
echo "*******************${w}"
ssh $node_name "sudo apt-get install libncurses-dev -y"
bcf_tools_tar=/node_temp/bcftools-1.11.tar.bz2
bcf_tools_path=/node_temp/bcftools-1.11/
bcf_tools_URL=https://github.com/samtools/bcftools/releases/download/1.11/bcftools-1.11.tar.bz2
ssh $node_name "chown -R $user_name:$user_name /node_temp/"
ssh $node_name "cd /node_temp/ && wget $bcf_tools_URL"
ssh $node_name "cd /node_temp/ && tar xjf  $bcf_tools_tar"
ssh $node_name "cd $bcf_tools_path && ./configure"
ssh $node_name "cd $bcf_tools_path && make -j $threads prefix=/usr/local/bin install"
ssh $node_name "cd $bcf_tools_path && make install -j $threads"
ssh $node_name "rm -rf /usr/bin/bcftools"
ssh $node_name "sudo ln -s /usr/local/bin/bin/bcftools /usr/bin/bcftools"
ssh $node_name "rm -rf $bcf_tools_path $bcf_tools_tar"
bcftools_v=`ssh $node_name bcftools -v | grep bcftools -A 1`

ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "---------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------${y}"
echo    "$bcftools_v"
echo    "${g}---------------------------------------------"
