#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Bowtie2
bowtie_path=/node_temp/bowtie2-2.4.2
bowtie_URL=https://github.com/BenLangmead/bowtie2/archive/refs/tags/v2.4.2.tar.gz
bowtie_zip=v2.4.2.tar.gz
ssh $node_name "su -c 'cd /node_temp/ && wget $bowtie_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $bowtie_zip' $user_name"
ssh $node_name "su -c 'cd $bowtie_path && make -j $threads' $user_name"
ssh $node_name "cd $bowtie_path && sudo make install -j $threads"
ssh $node_name "rm -rf $bowtie_path /node_temp/bowtie*"

ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "----------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------${y}"
ssh $node_name bowtie2 --version | grep bowtie
echo    "${g}---------------------------------------------"
