#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Jellyfish
echo "${y}*******************"
echo 'Jellyfish'
echo "*******************${w}"
jellyfish_path=/node_temp/jellyfish-2.3.0
jellyfish_tar=jellyfish-2.3.0.tar.gz
jellyfish_URL=https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz
#ssh $node_name "su -c 'cd /node_temp/ && wget $jellyfish_URL' $user_name"
ssh $node_name "su -c 'aria2c --file-allocation=none --show-console-readout false -c -x 8 -s 8 -d "/node_temp/" $jellyfish_URL' $user_name" 
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $jellyfish_tar' $user_name"
ssh $node_name "su -c 'cd $jellyfish_path && ./configure' $user_name"
ssh $node_name "su -c 'cd $jellyfish_path && make -j $threads' $user_name"
ssh $node_name "cd $jellyfish_path && sudo make install -j $threads"
ssh $node_name "rm -rf $jellyfish_path /node_temp/jellyfish-*z"

ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "---------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------${y}"
ssh $node_name jellyfish --version
echo    "${g}---------------------------------------------"
