#!/bin/bash

w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3)

USAGE="USAGE: $0"
if [ "$#" -ne "0" ]; then 
    echo -e $USAGE;
    exit 1
fi

user_name=$(whoami)
threads=$(sysctl -n hw.ncpu)

echo "${y}$USAGE ${g}"
echo "----------------------------------------------------------------------------------"
echo "-------------------- Installing Trinity and necessary packages --------------------"
echo "----------------------------------------------------------------------------------"
echo "Username:${w}"
echo "${w}"
echo "$user_name"

echo "${g}----------------------------------------------------------------------------------"
echo "${w}"

# Install Homebrew if not installed
if ! command -v brew &> /dev/null; then
    echo "Homebrew not found. Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Installing necessary packages
echo "Installing necessary packages..."
brew update
brew install gcc ncurses zlib xz cmake perl python@3.9 git libtbb openssl
pip3 install --upgrade setuptools numpy biopython
brew install bcftools pcre r samtools jellyfish bowtie2

# Clone Corset-tools repository
echo "Cloning Corset-tools repository..."
cd ~
rm -rf Corset-tools
git clone https://github.com/patrick-douglas/Corset-tools.git

# Execute additional scripts
echo "Executing additional scripts..."
cd Corset-tools
#./R-packages
#./java
#./ncbi-blast+
#./trinity-rna-seq
#./sft-ver

echo 'Latest version of HPC Grid Runner from GitHub'
echo "---------------------------------------------"
echo " "
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------------------- Main configuration completed -------------------------------"
echo "----------------------------------------------------------------------------------"
echo "----------------------------------------------------------------------------------"
echo "Support via email to patrick@ufpa.br"
echo 'Thank you :-D'
echo " "
echo "
                 ___        ______    __     __
                |   |      |	  \  |  \   |  | 
                |   |      |   D   ) |   \  |  | 
                |   |      |      /  |    \ |  | 
                |   |____  |      \  |  |\ \|  | 
                |        | |   D   ) |  | \    |  
                |________| |______/  |__|  \___|

     Molecular Biology and Neuroecology Laboratory - IFPA 
"
