#!/bin/bash

# Check if Homebrew is installed
if ! command -v brew &> /dev/null; then
	echo "Homebrew not found. Installing Homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Installing dependencies
echo "Installing dependencies..."
brew install bowtie
brew install samtools
brew install gcc

# Create symlinks for compilers
sudo ln -fs /opt/homebrew/Cellar/gcc/14.1.0_1/bin/g++-14 /usr/local/bin/g++-14
sudo ln -fs /opt/homebrew/Cellar/gcc/14.1.0_1/bin/gcc-14 /usr/local/bin/gcc-14

# Removing previous download files
echo "Removing previous download files..."
rm -rf trinityrnaseq trinityrnaseq-v* salmon boost

# Create a hidden temporary download folder
TMP_DOWNLOAD_FOLDER=~/.tmp_download
mkdir -p $TMP_DOWNLOAD_FOLDER

# Install Boost in the temporary download folder
echo "Installing Boost..."
cd $TMP_DOWNLOAD_FOLDER
git clone --recursive https://github.com/boostorg/boost.git
cd boost
./bootstrap.sh --prefix=$TRINITY_HOME/boost
./b2 install

# Get the number of CPU cores
NUM_THREADS=$(sysctl -n hw.ncpu)

# Install Salmon in the temporary download folder
echo "Installing Salmon..."
git clone https://github.com/COMBINE-lab/salmon.git
cd salmon
mkdir build && cd build
cmake -DBOOST_ROOT=$TMP_DOWNLOAD_FOLDER/boost -DCMAKE_INSTALL_PREFIX=$TMP_DOWNLOAD_FOLDER/salmon ..
make -j$NUM_THREADS
make install
cd ../..
rm -rf salmon
rm -rf boost

# Download and extract the latest release of Trinity
echo "Downloading and extracting the latest release of Trinity..."
cd ~/
curl -OL https://github.com/trinityrnaseq/trinityrnaseq/releases/latest/download/trinityrnaseq-latest.tar.gz
tar -xzvf trinityrnaseq-latest.tar.gz
rm trinityrnaseq-latest.tar.gz

# Compile Trinity
echo "Compiling Trinity..."
cd trinityrnaseq*
make -j $NUM_THREADS

# Get the path of the current directory's build folder
TRINITY_HOME=$(pwd)

# Add Trinity's build folder path to .bashrc if it's not already added
if ! grep -q "export TRINITY_HOME=$TRINITY_HOME" ~/.bashrc || ! grep -q 'export PATH=$PATH:$TRINITY_HOME' ~/.bashrc; then
	echo "export TRINITY_HOME=$TRINITY_HOME" >> ~/.bashrc
	echo 'export PATH=$PATH:$TRINITY_HOME' >> ~/.bashrc
	source ~/.bashrc
fi

echo "Trinity compiled successfully!"

# Remove temporary download folder and installation directories of Boost and Salmon
echo "Cleaning up temporary files..."
rm -rf $TMP_DOWNLOAD_FOLDER
rm -rf $TRINITY_HOME/boost
rm -rf $TRINITY_HOME/salmon

echo "Cleanup completed!"
