#!/bin/bash
#Este script é executado atraves de um script primario
rm -rf /home/.tmp/
mkdir -p /home/.tmp/
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3)
p=$(tput setaf 5)
pb=$(tput bold)

USAGE="USAGE: $0 -c <cluster_name> -p <ldappassword> -u <username> -w <networkinterfacename> -n <nodename> -i <node IP address>"

if [ "$#" -lt "6" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts c:n:p:u:w:i: option
do
case "${option}"
in
c) cluster_name=${OPTARG};;
n) node_name=${OPTARG};;
i) node_ip=${OPTARG};;
p) ldappassword=${OPTARG};;
u) user_name=$OPTARG;;
w) networkinterface=$OPTARG;;
esac
done

if [ "$cluster_name" = "" ]; then
"${g}Error, missing arguments:${y} -c | Cluster domain name | <string>
${w}$USAGE"
exit 1
fi

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi

if [ "$node_ip" = "" ]; then
"${g}Error, missing arguments:${y} -i | Node IP addres | <string>
${w}$USAGE"
exit 1
fi

if [ "$ldappassword" = "" ]; then
"${g}Error, missing arguments:${y} -p | ldap password | <string>
${w}$USAGE"
exit 1
fi

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

if [ "$networkinterface" = "" ]; then
"${g}Error, missing arguments:${y} -w | Network interface name | <string>
${w}$USAGE"
exit 1
fi

echo "${y}"
echo	"---------------------------------------------------------------------------------"
echo    "----------------- Phase 1: Identify the Cluster and the node --------------------"
echo    "---------------------------------------------------------------------------------"
echo 	""
echo    "---------------------------------------------------------------------------------"
echo	"${g}Cluster name:${w}"	
echo	"$cluster_name"
echo	"${g}New hostname:${w}"
echo	"$node_name"
echo	"${g}Node IP address:${w}"
echo	"$node_ip"
echo	"${g}LDAP password:${w}"
echo	"$ldappassword"
echo	"${g}User name:${w}"
echo	"$user_name"
echo	"${g}network interface name:${w}"
echo	"$networkinterface"
echo "${g}---------------------------------------------------------------------"
echo "${w}"
#Stage 1
cd 1-cluster-setup
./cluster_setup -c $cluster_name -p $ldappassword -u $user_name -w $networkinterface -n $node_name -i $node_ip
echo "${g}"
echo "----------------------------------------------------------"
echo "${p}$node_name ${g}was rebooted, waiting until it is online."
echo "----------------------------------------------------------${w}"

sleep 5 && ssh $node_name -q "exit" 
while test $? -gt 0
do
   sleep 10
   echo "Trying ssh to${y} $node_name${g}..."
   ssh $node_name -q "exit"
done
#Stage 2
sleep 5 && ssh $node_name -q "exit" 
while test $? -gt 0
do
   sleep 10
   echo "Trying ssh to${y} $node_name${g}..."
   ssh $node_name -q "exit"
done
cd ../2-mpich-slurm
./0-main -n $node_name -c $cluster_name -u $user_name
#Stage 3
sleep 5 && ssh $node_name -q "exit" 
while test $? -gt 0
do
   sleep 10
   echo "Trying ssh to${y} $node_name${g}..."
   ssh $node_name -q "exit"
done
cd ../3-bioinformatics
./0-update-inst-req-pkg -n $node_name -u $user_name
