#!/bin/bash
#Este script é executado atraves de um script primario
#second opt Set up only torque in the nodes

w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3)
p=$(tput setaf 5)  

USAGE="$0 -n <nodename> -c <clustername> -u <username>"

if [ "$#" -lt "4" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:c:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
c) cluster_name=${OPTARG};;
u) user_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"Error, missing arguments
Try: $USAGE"
exit 1
fi
if [ "$cluster_name" = "" ]; then
"Error, missing arguments
Try: $USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"Error, missing arguments
Try: $USAGE"
exit 1
fi

echo -e "${g}"
echo	"-----------------------------------------------------------------------------------"
echo    "------------------------------- Configuring node ----------------------------------"
echo    "-----------------------------------------------------------------------------------"
echo "Node name to connect:${w}"
echo "$node_name"
echo "${g}Cluster name:${w}"
echo "$cluster_name"
echo "${g}User name:${w}"
echo "$user_name"
echo "${g}----------------------------------------------------------------------------------"
ssh $node_name 'locale-gen pt_BR.UTF-8'
./1-mpich -n $node_name
./2-slurm -n $node_name -u $user_name -c $cluster_name
