#!/bin/bash
mkdir -p /home/.tmp/
#color defaults 
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
o=$(tput setaf 3) 
p=$(tput setaf 5)

USAGE="USAGE: $0 -u <username>"

if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User domain name | <string>
${w}$USAGE"
exit 1
fi

echo "${g}"  # set fg g
echo	"=================================${w}"
echo	"Testing your network connection${g}"
echo	"================================="
#function of slash spin
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

( wget -q --tries=10 --timeout=20 --spider http://google.com ) &
echo -n "Please wait... "
spinner $!
echo "DONE!${w}"

if [[ $? -eq 0 ]]; then
echo ""
echo "Connection OK"
echo "${g}"
else
echo "
Ouch!!!
--------------------------------------------------------------------------------------------------------
You are OFFLINE, your computer need to be connected to the Internet to install updates and some packages
If you continue without INTERNET connection the installation will no work
--------------------------------------------------------------------------------------------------------
"
function pause(){
   read -p "$*"
}
echo -e "setf 4" | tput -S
pause 'Connect to the Internet and Press [Enter] key to continue or [Ctrl+C] to exit.'
fi

#User name 
echo ""
echo "==============================================================="
echo "User name (Example me):${w}"
echo "$user_name ${g}"
echo "==============================================================="
echo "${w}"
apt-get update

#Configure ssh keygen
echo "${g}"
echo "==============================================================="
echo "===================Configuring ssh server======================"
echo "==============================================================="
echo "${w}"
cd && rm -rf .ssh
ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa
cd
cd .ssh
cp id_rsa.pub authorized_keys
cd
cp .ssh/ /home/$user_name/ -r
chown -R $user_name /home/$user_name/

#Configuring NFS
echo "${g}"
echo "==============================================================="
echo "=====================Configuring NFS==========================="
echo "==============================================================="
echo "${w}"



apt-fast install nfs-kernel-server -y

	LINE5='/root 11.0.0.0/8(rw,async,no_root_squash)'
	FILE5=/etc/exports
	grep -q "$LINE5" "$FILE5" || echo "$LINE5" >> "$FILE5"

	LINE6='/home 11.0.0.0/8(rw,async,no_root_squash)'
	FILE6=/etc/exports
	grep -q "$LINE6" "$FILE6" || echo "$LINE6" >> "$FILE6"

	LINE7='/export 11.0.0.0/8(rw,no_root_squash,async)'
	FILE7=/etc/exports
	grep -q "$LINE7" "$FILE7" || echo "$LINE7" >> "$FILE7"

mkdir -p /export

exportfs -va


#Configuring NTP
sed -i "/restrict ::1/ a \restrict 11.0.0.0 mask 255.255.255.0 nomodify notrap" /etc/ntp.conf
sed -i '43d' /etc/ntp.conf
service ntp start

