#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 

USAGE="USAGE: $0 -n <nodename>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done
echo	"${g}-----------------------------------------------------------------------------------"
echo    "----------------------------- Configuring MPICH 3.4 -------------------------------"
echo    "-----------------------------------------------------------------------------------"
echo "${w}"
echo "$node_name"
echo "${g}-----------------------------------------------------------------------------------"
echo "${w}"
ssh $node_name 'locale-gen pt_BR.UTF-8'
ssh $node_name 'apt-get --fix-broken install -y'
ssh $node_name apt-fast install --yes build-essential apt-utils zlib1g-dev perl perl-base  git libtbb-dev libxml2-dev libssl-dev g++ libssl-dev libxml2-dev libatlas-base-dev libboost-all-dev gfortran libibverbs-dev

#create temporary folder
ssh $node_name "rm -rf /.tmp/"
ssh $node_name "mkdir -p /.tmp"

# Download and install hwloc
hwloc_url=https://master.dl.sourceforge.net/project/rock64-dependencies/hwloc/hwloc_2.7.0-1_arm64.deb
hwloc_deb=hwloc_2.7.0-1_arm64.deb
ssh $node_name "cd /.tmp/ &&  wget $hwloc_url"
ssh $node_name "cd /.tmp/ && dpkg -i $hwloc_deb"

#Download AND install MPI 
ssh $node_name "mkdir -p /exports/mpich2"
mpich_deb_url=https://master.dl.sourceforge.net/project/rock64-dependencies/mpich/mpich_4.0rc3-1_arm64.deb
mpich_deb=mpich_4.0rc3-1_arm64.deb
ssh $node_name "cd /.tmp/ && wget $mpich_deb_url"
ssh $node_name "cd /.tmp/ && dpkg -i $mpich_deb"

echo "${g}"
echo	"----------------------------------------------------------------------------------"
echo    "---------------------  MPICH 3.4 reconfigured successfully -----------------------"
echo    "----------------------------------------------------------------------------------"	
echo	"MPICH 3.4 configured in the${w} $node_name"
echo	""
ssh $node_name "rm -rf /.tmp/"

