#!/bin/bash
#Este script é executado atraves de um script primario

w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

echo -e "${g}"
echo	"-----------------------------------------------------------------------------------"
echo    "---------------------- Configuring Bioinformatics softwares -----------------------"
echo    "-----------------------------------------------------------------------------------"
echo	"${g}Node hostname:${w}"
echo	"$node_name"
echo	"${g}User name:${w}"
echo	"$user_name"
echo "${g}------------------------------------------------------------------------------------"
echo -e "${w}"
#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Master home mount
ssh $node_name 'mount master:/home /home'

#Java
#ssh $node_name 'add-apt-repository ppa:linuxuprising/java -y && apt-fast update'
#ssh $node_name 'echo oracle-java16-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections'
#ssh $node_name 'sudo apt-get -y install oracle-java16-installer'
#ssh $node_name 'sudo apt install oracle-java16-set-default'

ssh $node_name "apt-fast install -y software-properties-common debconf-utils"
ssh $node_name 'DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-fast -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade'
#ssh $node_name "apt-fast -y install default-jdk"
ssh $node_name "apt-fast update -qq"

#Required packages
ssh $node_name "apt-fast install -y gcc libncurses5-dev zlib1g-dev build-essential libxml2-dev build-essential fort77 xorg-dev liblzma-dev libblas-dev gfortran gcc-multilib gobjc++ libcurl4-gnutls-dev aptitude libreadline-dev libbz2-dev libssl-dev gedit libcairo2-dev libgtk2.0-dev"
ssh $node_name 'apt-fast install --yes apt-utils perl perl-base git libtbb-dev build-essential libtool -y'
ssh $node_name "aptitude install libreadline-dev -y"
ssh $node_name "/usr/local/bin/pip3 install numpy"
ssh $node_name "/usr/local/bin/pip3 install --upgrade pip"
#ssh $node_name "python -m pip install -U matplotlib"
ssh $node_name "apt-get install python-setuptools -y"
ssh $node_name "apt-get install python3-setuptools -y"
ssh $node_name "/usr/local/bin/pip3 install gffutils"


./1-hmmer -n $node_name -u $user_name
./2-bzip2 -n $node_name -u $user_name
./3-xz -n $node_name -u $user_name
./4-bcftools -n $node_name -u $user_name
./5-htslib -n $node_name -u $user_name
./6-samtools -n $node_name -u $user_name
./7-cmake -n $node_name -u $user_name
./8-pcre -n $node_name -u $user_name
./9-R -n $node_name -u $user_name
./10-Jellyfish -n $node_name -u $user_name
./11-salmon -n $node_name -u $user_name
./12-bowtie2 -n $node_name -u $user_name
./13-parafly -n $node_name -u $user_name
./14-blast+ -n $node_name -u $user_name
./15-trinity-rnaseq -n $node_name -u $user_name
./16-seqtk -n $node_name -u $user_name
./17-python3 -n $node_name -u $user_name

ssh $node_name 'rm -rf /node_temp/'
echo	" "
echo -e "setf 6" | tput -S
echo	"----------------------------------------------------------------------------------"
echo    "---------------------- We finished the node configuration ------------------------"
echo    "----------------------------------------------------------------------------------"
echo -e "setf 6" | tput -S
echo	"support by e-mail to patrick@ufpa.br"
echo    'Thank you :-D'
echo	" "
echo "
				 ___        ______    __     __
				|   |      |	  \  |  \   |  | 
				|   |      |   D   ) |   \  |  | 
				|   |      |      /  |    \ |  | 
				|   |____  |      \  |  |\ \|  | 
				|        | |   D   ) |  | \    |  
				|________| |______/  |__|  \___|

     Laboratório de Biologia Molecular e Neuroecologia - IFPA"

./sft-ver -n $node_name













