#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Parafly 
parafly_path=/node_temp/ParaFly-0.1.0
parafly_tar=/node_temp/v0.1.0.tar.gz
parafly_tar_URL=https://github.com/ParaFly/ParaFly/archive/refs/tags/v0.1.0.tar.gz
ssh $node_name "su -c 'cd /node_temp/ && wget $parafly_tar_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $parafly_tar' $user_name"
ssh $node_name "su -c 'cd $parafly_path && ./configure' $user_name"
ssh $node_name "su -c 'cd $parafly_path && make -j $threads' $user_name"
ssh $node_name "cd $parafly_path && sudo make install -j $threads"
ssh $node_name "rm -rf $parafly_path $parafly_tar"
echo "$parafly_tar" | sed 's/.[^.]*//6g' > .pfly
pfly_v=`cat .pfly` && rm -rf .pfly
pfly_ver=`basename $pfly_v`

ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "----------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------${y}"
echo    "$pfly_ver"
echo    "${g}---------------------------------------------"
