#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#python
echo "${y}*******************"
echo 'Python3.9'
echo "*******************${w}"
python_path=/node_temp/Python-3.9.0
python_tar=Python-3.9.0.tar.xz
python_tar_URL=https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz

#remove old version
ssh $node_name "su -c 'cd /node_temp/ && wget $python_tar_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -xf $python_tar' $user_name"
ssh $node_name "su -c 'cd $python_path && ./configure --enable-optimizations' $user_name"
ssh $node_name "su -c 'cd $python_path && make -j $threads' $user_name"
ssh $node_name "cd $python_path && sudo make install -j $threads"
ssh $node_name "rm -rf $python_path /node_temp/$python_tar"
python_version=`ssh $node_name python3.9 --version`


ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "--------------------------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------------------------${y}"
echo    "$python_version"
echo    "${g}---------------------------------------------------------------------"
