#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Xz
echo "${y}*******************"
echo 'xz utils'
echo "*******************${w}"
xz_path=/node_temp/xz-5.2.5/
xz_tar=/node_temp/xz-5.2.5.tar.gz
xz_tar_URL=https://sonik.dl.sourceforge.net/project/lzmautils/xz-5.2.5.tar.gz
ssh $node_name "su -c 'cd /node_temp/ && wget $xz_tar_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $xz_tar' $user_name"
ssh $node_name "su -c 'cd $xz_path && ./configure' $user_name"
ssh $node_name "su -c 'cd $xz_path && make -j $threads' $user_name"
ssh $node_name "cd $xz_path && make install -j $threads"
ssh $node_name "rm -rf $xz_path $xz_tar"
xz_v=`ssh $node_name xz -V | grep xz`


ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "---------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------${y}"
echo    "$xz_v"
echo    "${g}---------------------------------------------"
