#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#cmake
echo "${y}*******************"
echo 'cmake'
echo "*******************${w}"
cmake_tar=/node_temp/cmake-3.18.4.tar.gz
cmake_path=/node_temp/cmake-3.18.4
cmake_URL=https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4.tar.gz

ssh $node_name "su -c 'cd /node_temp/ && wget $cmake_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $cmake_tar' $user_name"
ssh $node_name "su -c 'cd $cmake_path && ./configure' $user_name"
ssh $node_name "su -c 'cd $cmake_path && make -j $threads' $user_name"
ssh $node_name "cd $cmake_path && make install -j $threads"
ssh $node_name "rm -rf $cmake_path $cmake_tar"
cmake_v=`ssh $node_name cmake --version | grep version`


ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "---------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------${y}"
echo    "$cmake_v"
echo    "${g}---------------------------------------------"
