#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#pcre
echo "${y}*******************"
echo 'pcre'
echo "*******************${w}"
PCRE_path=/node_temp/pcre-8.43
PCRE_tar=/node_temp/pcre-8.43.tar.gz
PCRE_URL=https://ftp.pcre.org/pub/pcre/pcre-8.43.tar.gz
ssh $node_name "su -c 'cd /node_temp/ && wget $PCRE_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $PCRE_tar' $user_name"
ssh $node_name "su -c 'cd $PCRE_path && ./configure --enable-utf8' $user_name"
ssh $node_name "su -c 'cd $PCRE_path && make -j $threads' $user_name"
ssh $node_name "cd $PCRE_path && sudo make install -j $threads"
#pcre2
echo "${y}*******************"
echo 'pcre2'
echo "*******************${w}"
PCRE2_path=/node_temp/pcre2-10.34/
PCRE2_tar=/node_temp/pcre2-10.34.tar.gz
PCRE2_URL=https://ftp.pcre.org/pub/pcre/pcre2-10.34.tar.gz
ssh $node_name "su -c 'cd /node_temp/ && wget $PCRE2_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $PCRE2_tar' $user_name"
ssh $node_name "su -c 'cd $PCRE2_path && ./configure --enable-utf8' $user_name"
ssh $node_name "su -c 'cd $PCRE2_path && make -j $threads' $user_name"
ssh $node_name "cd $PCRE2_path && sudo make install -j $threads"

ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "---------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------${y}"
echo -n -e 'pcre ' && pcre-config --version
echo -n -e 'pcre2 ' && pcre2-config --version
echo    "${g}---------------------------------------------"
