#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#R update
echo "${y}*******************"
echo 'R'
echo "*******************${w}"
ssh $node_name "sudo apt-fast install -y build-essential fort77 xorg-dev liblzma-dev  libblas-dev gfortran gcc-multilib gobjc++ libcurl4-openssl-dev"
ssh $node_name "sudo apt-get install aptitude -y"
ssh $node_name "sudo aptitude install libreadline-dev -y"
R_path=/node_temp/R-4.0.3
R_tar=R-4.0.3.tar.gz
R_URL=https://cran.r-project.org/src/base/R-4/R-4.0.3.tar.gz
ssh $node_name "su -c 'cd /node_temp/ && wget $R_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && tar -zxf $R_tar' $user_name"
ssh $node_name "su -c 'cd $R_path && ./configure' $user_name"
ssh $node_name "su -c 'cd $R_path && make -j $threads' $user_name"
ssh $node_name "cd $R_path && sudo make install -j $threads"
ssh $node_name "rm -rf $R_path /node_temp/$R_tar"

ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "---------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------${y}"
ssh $node_name R --version | grep version | grep R
echo    "${g}---------------------------------------------"
