#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
echo    "${g}---------------"
echo	"Node hostname:${w}"
echo	"$node_name"
echo "${g}---------------"
echo -e "${w}"
echo "${y}**********************"
echo 'Java'
echo "**********************${w}"
ssh $node_name 'java -version' 
echo "${y}**********************"
echo 'Software versions'
echo "**********************${w}" 
paste <(echo 'hmmer      ') <(ssh $node_name "hmmscan -h | grep HMMER | awk '{print \$3}'")
paste <(echo 'XZ utils   ') <(ssh $node_name "xz -V | grep XZ | awk '{print \$4}'")
paste <(echo 'bcftools   ') <(ssh $node_name "bcftools --version | grep bcftools | awk '{print \$2}'" )
paste <(echo 'htslib   ') <(ssh $node_name 'samtools --version | grep htslib' | awk '{print $3}')
paste <(echo 'samtools') <(ssh $node_name 'samtools --version | grep samtools' | awk '{print $2}')
paste <(echo 'cmake      ') <(ssh $node_name 'cmake --version | grep version' | awk '{print $3}')
paste <(echo 'pcre      ') <(ssh $node_name 'pcre-config --version')
paste <(echo 'pcre2      ') <(ssh $node_name "pcre2-config --version")
paste <(echo 'R            ') <(ssh $node_name 'R --version | grep version | grep R' | awk '{print $3}')
paste <(echo 'Jellyfish      ') <(ssh $node_name "jellyfish --version | awk '{print \$2}'")
paste <(echo 'bowtie2      ') <(ssh $node_name "bowtie2 --version | grep version | grep bowtie | awk '{print \$NF}' FS=/ | awk '{print \$3}'")
paste <(echo 'Trinity      ') <(ssh $node_name "/usr/local/bin/Trinity --version | grep - | grep v2 | awk '{print \$3}' | awk '{print \$NF}' FS='-'| sed 's/v//'  | head -n 1")
paste <(echo 'Salmon      ') <(ssh $node_name "salmon -v | awk '{print \$2}'")
paste <(echo 'ncbi-blast+  ') <(ssh $node_name "blastx -version | grep Pack | awk '{print \$NF}' FS=': '" | awk '{print $2}' | sed 's/,//' )
paste <(echo 'Python3      ') <(ssh $node_name "python3.9 --version | awk '{print \$2}'")
echo "${y}**********************${w}" 




