#!/bin/bash
#Este script é executado atraves de um script primario

w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

echo -e "${g}"
echo	"-----------------------------------------------------------------------------------"
echo    "---------------------- Configuring Bioinformatics softwares -----------------------"
echo    "-----------------------------------------------------------------------------------"
echo	"${g}Node hostname:${w}"
echo	"$node_name"
echo	"${g}User name:${w}"
echo	"$user_name"
echo "${g}------------------------------------------------------------------------------------"
echo -e "${w}"

#install required libs
echo "${g}************************************************"
echo "  ${w}Installing required libraries and packages${g}"
echo "************************************************${w}"
echo ''
echo -ne '##############                   (5.56%)\r'
echo -ne '###############                  (11.11%)\r'
echo -ne '################                 (16.67%)\r'
echo -ne '#################                (22.22%)\r'
echo -ne '##################               (27.78%)\r'
echo -ne '###################              (33.33%)\r'
echo -ne '####################             (38.89%)\r'
echo -ne '#####################            (44.44%)\r'
echo -ne '######################           (50.00%)\r'
echo -ne '#######################          (55.56%)\r'
echo -ne '########################         (61.11%)\r'
echo -ne '#########################        (66.67%)\r'
echo -ne '##########################       (72.22%)\r'
echo -ne '###########################      (77.78%)\r'
echo -ne '############################     (83.33%)\r'
echo -ne '#############################    (88.89%)\r'
echo -ne '##############################   (94.44%)\r'
echo -ne '################################ (100.00%)\r'


#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Master home mount
ssh $node_name 'mount master:/home /home'

#Java
#ssh $node_name 'add-apt-repository ppa:linuxuprising/java -y && apt-fast update'
#ssh $node_name 'echo oracle-java16-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections'
#ssh $node_name 'sudo apt-get -y install oracle-java16-installer'
#ssh $node_name 'sudo apt install oracle-java16-set-default'

ssh $node_name "apt-fast install -y software-properties-common debconf-utils"
ssh $node_name 'DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-fast -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade'
#ssh $node_name "apt-fast -y install default-jdk"
ssh $node_name "apt-fast update -qq"

#Required packages
ssh $node_name "apt-fast install -y gcc libncurses5-dev zlib1g-dev build-essential libxml2-dev build-essential fort77 xorg-dev liblzma-dev libblas-dev gfortran gcc-multilib gobjc++ libcurl4-gnutls-dev aptitude libreadline-dev libbz2-dev libssl-dev gedit libcairo2-dev libgtk2.0-dev"
ssh $node_name 'apt-fast install --yes apt-utils perl perl-base git libtbb-dev build-essential libtool -y'
ssh $node_name "aptitude install libreadline-dev -y"
ssh $node_name "/usr/local/bin/pip3 install numpy"
ssh $node_name "/usr/local/bin/pip3 install --upgrade pip"
ssh $node_name "apt-get install python-setuptools -y"
ssh $node_name "apt-get install python3-setuptools -y"
ssh $node_name "/usr/local/bin/pip3 install gffutils"

echo -ne '###                                      (8.33%)\r'
./hmmer -n $node_name -u $user_name
./bzip2 -n $node_name -u $user_name
./xz -n $node_name -u $user_name
./bcftools -n $node_name -u $user_name
./htslib -n $node_name -u $user_name
./samtools -n $node_name -u $user_name
./cmake -n $node_name -u $user_name
./pcre -n $node_name -u $user_name
./R -n $node_name -u $user_name
./Jellyfish -n $node_name -u $user_name
./salmon -n $node_name -u $user_name
./bowtie2 -n $node_name -u $user_name
./parafly -n $node_name -u $user_name
./blast+ -n $node_name -u $user_name
./seqtk -n $node_name -u $user_name
./python3 -n $node_name -u $user_name
./trinity-rnaseq -n $node_name -u $user_name
echo -ne '#######################################(100.00%)\r'
ssh $node_name 'rm -rf /node_temp/'


ssh $node_name "/usr/local/bin/pip3 install numpy"
ssh $node_name "/usr/local/bin/pip3 install --upgrade pip"
ssh $node_name "/usr/local/bin/pip3 install gffutils"
ssh $node_name "python -m pip install -U matplotlib"

echo	" "
echo -e "setf 6" | tput -S
echo	"----------------------------------------------------------------------------------"
echo    "---------------------- We finished the node configuration ------------------------"
echo    "----------------------------------------------------------------------------------"
echo -e "setf 6" | tput -S
echo	"support by e-mail to patrick@ufpa.br"
echo    'Thank you :-D'
echo	" "
echo "
				 ___        ______    __     __
				|   |      |	  \  |  \   |  | 
				|   |      |   D   ) |   \  |  | 
				|   |      |      /  |    \ |  | 
				|   |____  |      \  |  |\ \|  | 
				|        | |   D   ) |  | \    |  
				|________| |______/  |__|  \___|

     Laboratório de Biologia Molecular e Neuroecologia - IFPA"

./sft-ver -n $node_name













