#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
rm -rf /.tmp/

USAGE="USAGE: $0 -n <nodename>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done
echo	"${g}-----------------------------------------------------------------------------------"
echo    "----------------------------- Configuring MPICH 3.2 -------------------------------"
echo    "-----------------------------------------------------------------------------------"
echo "${w}"
echo "$node_name"
echo "${g}----------------------------------------------------------------------------------"
echo " "
echo "${w}"
ssh $node_name apt-fast install --yes build-essential gcc-multilib apt-utils zlib1g-dev perl perl-base git libtbb-dev libxml2-dev bowtie2 libssl-dev g++ libssl-dev libxml2-dev libatlas-base-dev libboost-all-dev gfortran -y
#Set -j option during make process

threads=`ssh $node_name nproc`
#Set mpich $PATH
mpich_path=/.tmp/mpich-3.2.1/
mpich_tar=/.tmp/mpich-3.2.1.tar.gz
ssh $node_name "mkdir -p /.tmp"
ssh $node_name "mkdir -p /exports/mpich2"
ssh $node_name "rm -rf $mpich_tar"
ssh $node_name "cd /.tmp/ && wget http://www.mpich.org/static/downloads/3.2.1/mpich-3.2.1.tar.gz"
ssh $node_name "cd /.tmp/ && tar zxf $mpich_tar"
ssh $node_name "cd $mpich_path && ./configure --prefix=/exports/mpich2"
ssh $node_name "cd $mpich_path && make -j $threads"
ssh $node_name "cd $mpich_path && make install -j $threads"
ssh $node_name "rm -rf $mpich_tar"

echo "${g}"
echo	"----------------------------------------------------------------------------------"
echo    "---------------------  MPICH 3.2 reconfigured successfully -----------------------"
echo    "----------------------------------------------------------------------------------"	
echo	"MPICH 3.2 configured in the${w} $node_name"
echo	""
ssh $node_name "rm -rf /.tmp/"

