#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
echo    "${g}---------------"
echo	"Node hostname:${w}"
echo	"$node_name"
echo "${g}---------------"
echo -e "${w}"
ssh $node_name "mkdir -p /node_temp/"
#Jellyfish
echo "${y}*******************"
echo 'Jellyfish'
echo "*******************${w}"
jellyfish_deb_URL=https://master.dl.sourceforge.net/project/rock64-dependencies/jellyfish/jellyfish_2.3.0-1_arm64.deb
jellyfish_deb=jellyfish_2.3.0-1_arm64.deb
ssh $node_name "cd /node_temp && wget --show-progress $jellyfish_deb_URL"
ssh $node_name "dpkg -i /node_temp/$jellyfish_deb"
ssh $node_name "ldconfig"
jellyfish_version=`ssh $node_name jellyfish --version`
ssh $node_name "rm -rf /node_temp/"
