#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
echo    "${g}---------------"
echo	"Node hostname:${w}"
echo	"$node_name"
echo "${g}---------------"
echo -e "${w}"
ssh $node_name "mkdir -p /node_temp/"
#Bowtie2
echo "${y}*******************"
echo 'Bowtie2'
echo "*******************${w}"
bowtie2_deb_URL=https://master.dl.sourceforge.net/project/rock64-dependencies/bowtie2/bowtie2_2.3.4.1-1_arm64.deb
bowtie2_deb=bowtie2_2.3.4.1-1_arm64.deb
ssh $node_name "cd /node_temp && wget --show-progress $bowtie2_deb_URL"
ssh $node_name "dpkg -i /node_temp/$bowtie2_deb"
bowtie_v=`ssh $node_name bowtie2 --version | grep bowtie`
ssh $node_name "rm -rf /node_temp/"
