#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
echo    "${g}---------------"
echo	"Node hostname:${w}"
echo	"$node_name"
echo "${g}---------------"
echo -e "${w}"
ssh $node_name "mkdir -p /node_temp/"
#Parafly
echo "${y}*******************"
echo 'parafly'
echo "*******************${w}" 
parafly_deb_URL=https://master.dl.sourceforge.net/project/rock64-dependencies/parafly/parafly_0.0.2013.01.21-4_arm64.deb
parafly_deb=parafly_0.0.2013.01.21-4_arm64.deb
ssh $node_name "cd /node_temp && wget --show-progress $parafly_deb_URL"
ssh $node_name "dpkg -i /node_temp/$parafly_deb"
ssh $node_name "rm -rf /usr/local/bin/trinityrnaseq-latest/trinity-plugins/BIN/Parafly"
#ssh $node_name "ln -fs /usr/bin/ParaFly /usr/local/bin/trinityrnaseq-latest/trinity-plugins/BIN/Parafly"
echo "$parafly_deb" | sed 's/.[^.]*//6g' > .pfly
pfly_v=`cat .pfly` && rm -rf .pfly
pfly_ver=`basename $pfly_v`
ssh $node_name "rm -rf /node_temp/"
