#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
echo    "${g}---------------"
echo	"Node hostname:${w}"
echo	"$node_name"
echo "${g}---------------"
echo -e "${w}"
ssh $node_name "mkdir -p /node_temp/"
#bzip
echo "${y}*******************"
echo 'bzip2'
echo "*******************${w}"
bzip2_deb_URL=https://ufpr.dl.sourceforge.net/project/rock64-dependencies/bzip2/bzip2_1.0.6-1_arm64.deb
bzip2_deb=bzip2_1.0.6-1_arm64.deb
ssh $node_name "cd /node_temp/ && wget --show-progress $bzip2_deb_URL"
ssh $node_name "dpkg -i /node_temp/$bzip2_deb"
ssh $node_name "rm -rf /node_temp/"

