#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
echo    "${g}---------------"
echo	"Node hostname:${w}"
echo	"$node_name"
echo "${g}---------------"
echo -e "${w}"
ssh $node_name "mkdir -p /node_temp/"
echo "${y}*******************"
echo 'R-devel'
echo "*******************${w}"
R_deb_URL=https://master.dl.sourceforge.net/project/rock64-dependencies/R/r-devel_4.1.0-1_arm64.deb
R_deb=r-devel_4.1.0-1_arm64.deb
ssh $node_name "cd /node_temp && wget --show-progress $R_deb_URL"
ssh $node_name "dpkg --force-all -i /node_temp/$R_deb"
ssh $node_name "ldconfig"
mkdir -p /node_temp/

echo "${y}*******************"
echo 'R'
echo "*******************${w}"
R_deb_URL=https://master.dl.sourceforge.net/project/rock64-dependencies/R/r_4.0.5-1_arm64.deb
R_deb=r_4.0.5-1_arm64.deb
ssh $node_name "cd /node_temp && wget --show-progress $R_deb_URL"
ssh $node_name "dpkg --force-all -i /node_temp/$R_deb"
ssh $node_name "ldconfig"

