#!/bin/bash
#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
R_ver=`ssh $node_name 'R --version | grep version | grep R' | awk '{print $3}'`
echo -e "${w}"
echo "${w}********************************"
echo "R $R_ver packages versions"
echo "********************************${g}"
echo -n "${g}RCurl: 		        ${w}" ; ssh $node_name "R -e 'packageVersion(\"RCurl\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}annotate:		${w}" ; ssh $node_name "R -e 'packageVersion(\"annotate\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}GenomicRanges:		${w}" ; ssh $node_name "R -e 'packageVersion(\"GenomicRanges\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}SummarizedExperiment:	${w}" ; ssh $node_name "R -e 'packageVersion(\"SummarizedExperiment\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}genefilter:		${w}" ; ssh $node_name "R -e 'packageVersion(\"genefilter\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}DESeq2:		        ${w}" ; ssh $node_name "R -e 'packageVersion(\"DESeq2\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}Biobase:		${w}" ; ssh $node_name "R -e 'packageVersion(\"Biobase\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}gplots:        		${w}" ; ssh $node_name "R -e 'packageVersion(\"gplots\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}qvalue:        		${w}" ; ssh $node_name "R -e 'packageVersion(\"ape\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}qvalue:        		${w}" ; ssh $node_name "R -e 'packageVersion(\"qvalue\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}DEXSeq:        		${w}" ; ssh $node_name "R -e 'packageVersion(\"DEXSeq\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}fastcluster:		${w}" ; ssh $node_name "R -e 'packageVersion(\"fastcluster\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}Biobase:		${w}" ; ssh $node_name "R -e 'packageVersion(\"Biobase\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}argparse:		${w}" ; ssh $node_name "R -e 'packageVersion(\"argparse\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}seqLogo:		${w}" ; ssh $node_name "R -e 'packageVersion(\"seqLogo\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}EBSeq:     		${w}" ; ssh $node_name "R -e 'packageVersion(\"EBSeq\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}ggplot2:		${w}" ; ssh $node_name "R -e 'packageVersion(\"ggplot2\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}grid:      		${w}" ; ssh $node_name "R -e 'packageVersion(\"grid\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}dplyr:     		${w}" ; ssh $node_name "R -e 'packageVersion(\"dplyr\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo -n "${g}ggrepel:		${w}" ; ssh $node_name "R -e 'packageVersion(\"ggrepel\")'" | grep packageVersion -A 1 | awk {'print $2'} | sed -n '2p' | sed -r 's/^.{1}//' | sed 's/.$//'
echo "${w}********************************"

