#!/bin/bash
mkdir -p /home/.tmp/
#color defaults 
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5)

#root requirements
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "${y}-----------------------------------------------------------------------------------"
    echo "This script requires root privileges, please run${w} sudo su${y} or${w} sudo -i ${y}prior to run it"
    echo "e.g.${w} sudo $0 -c <clustername> -u <username> ${y}"
    echo "-----------------------------------------------------------------------------------"
    exit
fi

USAGE="USAGE: $0 -c <clustername> -u <username>"

if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts c:u: option
do
case "${option}"
in
c) cluster_name=$OPTARG;;
u) user_name=$OPTARG;;

esac
done

if [ "$cluster_name" = "" ]; then
echo -e "${g}Error, missing arguments:${y} -c | Cluster domain name | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
echo -e "${g}Error, missing arguments:${y} -u | User domain name | <string>
${w}$USAGE"
exit 1
fi

echo "${g}"  # set fg g
echo	"=================================${w}"
echo	"Testing your network connection${g}"
echo	"================================="
#function of slash spin
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

( wget -q --tries=10 --timeout=20 --spider http://google.com ) &
echo -n "Please wait... "
spinner $!
echo "DONE!${w}"

if [[ $? -eq 0 ]]; then
echo ""
echo "Connection OK"
echo "${g}"
else
echo "
Ouch!!!
--------------------------------------------------------------------------------------------------------
You are OFFLINE, your computer need to be connected to the Internet to install updates and some packages
If you continue without INTERNET connection the installation will no work
--------------------------------------------------------------------------------------------------------
"
function pause(){
   read -p "$*"
}
echo -e "setf 4" | tput -S
pause 'Connect to the Internet and Press [Enter] key to continue or [Ctrl+C] to exit.'
fi

echo	"${g}"
echo	"---------------------------------------------------------------------------------"
echo    "---------------------- Phase 1: Identify the Cluster ----------------------------"
echo    "---------------------------------------------------------------------------------"
	echo ""

echo ""

echo ""
echo "==============================================================="
echo "Cluster name or domain name (Example lbn):${w}"
echo "$cluster_name ${g}"
echo "==============================================================="
#User name 
echo ""
echo "==============================================================="
echo "User name (Example me):${w}"
echo "$user_name ${g}"
echo "==============================================================="
echo "${w}"
apt-get update
#apt-get install curl language-pack-pt -y
/bin/bash -c "$(curl -sL https://git.io/vokNn)"
sed -i 's/^#_MAXNUM=5/_MAXNUM=16/' /etc/apt-fast.conf
./1-mpich
./2-slurm -c $cluster_name -u $user_name

echo	" "
echo	" "
echo -e "setf 6" | tput -S
echo	"----------------------------------------------------------------------------------"
echo    "--------------------- We finhished the Master configuration ----------------------"
echo    "----------------------------------------------------------------------------------"
echo -e "setf 6" | tput -S
echo	"suport by e-mail to patrick@ufpa.br"
echo    'Thank you :-D'
echo	" "
echo "
				 ___        ______    __     __
				|   |      |	  \  |  \   |  | 
				|   |      |   D   ) |   \  |  | 
				|   |      |      /  |    \ |  | 
				|   |____  |      \  |  |\ \|  | 
				|        | |   D   ) |  | \    |  
				|________| |______/  |__|  \___|

     Laboratório de Biologia Molecular e Neuroecologia - IFPA 
"
