#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`
#cmake
echo "${y}*******************"
echo 'cmake'
echo "*******************${w}"

cmake_tar=/home/$user_name/cmake-3.23.0-rc1.tar.gz
cmake_path=/home/$user_name/cmake-3.23.0-rc1
cmake_url=https://github.com/Kitware/CMake/releases/download/v3.23.0-rc1/cmake-3.23.0-rc1.tar.gz

su -c "cd ~/ && wget $cmake_url" $user_name
su -c "cd ~/ && tar -zxf $cmake_tar" $user_name
su -c "cd $cmake_path && ./configure" $user_name
su -c "cd $cmake_path && make -j $threads" $user_name
cd $cmake_path && sudo make install -j $threads
rm -rf $cmake_path $cmake_tar && cd


echo "${g}"
echo    "---------------------------------------------------"
echo	"          Currently installed versions:"
echo    "---------------------------------------------------${w}"
cmake --version
echo    "${g}---------------------------------------------"
