#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`
#fastqC
echo "${y}*******************"
echo 'FastQC'
echo "*******************${w}"
FastQC_zip=/home/$user_name/fastqc_v0.12.1.zip
FastQC_path=/home/$user_name/FastQC
FastQC_url=https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip
rm -rf $FastQC_path
su -c "cd ~/ && wget $FastQC_url" $user_name
su -c "cd ~/ && unzip $FastQC_zip" $user_name
su -c "chmod +x $FastQC_path/fastqc" $user_name
rm -rf $FastQC_zip
FastQC_ver=`$FastQC_path/fastqc -v`

echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "---------------------------${w}"
/home/$user_name/FastQC/fastqc -v
echo    "${g}------------------------"
