#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`
#install required libs
echo "${y}*****************************"
echo 'Installing required libraries'
echo "*****************************${w}"
sudo apt-fast install -y build-essential fort77 liblzma-dev libblas-dev gfortran gcc-multilib gobjc++ aptitude libcurl4-openssl-dev libbz2-dev libproj-dev xorg-dev
sudo aptitude install -y libreadline-dev

#R update
echo "${y}*******************"
echo 'R'
echo "*******************${w}"
R_path=/home/$user_name/R-*.*.*
R_tar=R-latest.tar.gz
R_url=https://cran.r-project.org/src/base/R-latest.tar.gz
rm -rf $R_path $R_path.tar.gz
su -c "cd ~/ && wget $R_url" $user_name
su -c "cd ~/ && tar -zxf $R_tar" $user_name
rm -rf /home/$user_name/R-*.tar.gz
su -c "cd $R_path && ./configure --with-cairo" $user_name
su -c "cd $R_path && make -j $threads" $user_name
cd $R_path && sudo make uninstall -j $threads
cd $R_path && sudo make install -j $threads

chown -R $user_name:$user_name /home/$user_name
rm -rf $R_path /home/$user_name/$R_tar && cd

echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "---------------------------${w}"
R --version | grep version | grep R
echo    "${g}------------------------"

