#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#create temp dir
#Seqtk
seqtk_path=/home/$user_name/seqtk
seqtk_URL=https://github.com/lh3/seqtk.git
su -c "cd /home/$user_name/ && git clone $seqtk_URL;" $user_name
su -c "cd $seqtk_path && make" $user_name
cd $seqtk_path && sudo make install
rm -rf $seqtk_path
echo "${g}"
echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "----------------------------${w}"
seqtk | grep Version
echo    "${g}----------------------------"
