#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

#diamond
echo "${y}*******************"
echo 'diamond'
echo "*******************${w}"
diamond_url=https://github.com/bbuchfink/diamond/releases/download/v2.1.20/diamond-linux64.tar.gz
diamond_tar=/home/$user_name/diamond-linux64.tar.gz
diamond_bin=/home/$user_name/diamond

#rm -rf /usr/local/bin/diamondrnaseq-*
su -c "cd ~/ && wget $diamond_url" $user_name
su -c "cd ~/ && tar -zxf $diamond_tar" $user_name
sudo cp $diamond_bin /usr/local/bin/diamond
rm -rf $diamond_bin $diamond_tar

echo	""
echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "----------------------------${w}"
/usr/local/bin/diamond --version
echo    "${g}----------------------------"
