#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`
#HMMER
echo "${y}*******************"
echo 'HMMER'
echo "*******************${w}"
hmmer_tar=/home/$user_name/hmmer-3.3.2.tar.gz
hmmer_path=/home/$user_name/hmmer-3.3.2
hmmer_url=http://eddylab.org/software/hmmer/hmmer-3.3.2.tar.gz
su -c "cd ~/ && wget $hmmer_url" $user_name
su -c "cd ~/ && tar zxf $hmmer_tar" $user_name
su -c "cd $hmmer_path && ./configure" $user_name
su -c "cd $hmmer_path && make -j $threads" $user_name
cd $hmmer_path && sudo make install -j $threads
rm -rf $hmmer_tar $hmmer_path

echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "---------------------------${w}"
hmmscan -h | grep HMMER
echo    "${g}------------------------"

