#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

#AUGUSTUS
echo "${y}*******************"
echo 'Hpc Grid Runner'
echo "*******************${w}"

su -c "cd ~/ && git clone https://github.com/HpcGridRunner/HpcGridRunner.git" $user_name

echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "---------------------------${w}"
echo 'HPC Grid Runner Latest github Version'
echo    "${g}------------------------"
