#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

echo "${y}*******************"
echo 'ncbi-blast+'
echo "*******************${w}"
apt-fast install alien -y
blast_url=ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-*.x86_64.rpm
cd ~/ && wget $blast_url
echo "${y}**************************************************************"
echo "Creating a ncbi-blast+ .deb file, this may take a long time..."
echo "**************************************************************${w}"
cd ~/ && alien -v -d *.rpm
echo "${y}************************************************"
echo "instaling ncbi-blast+, this may take a long time"
echo "************************************************${w}"
cd ~/ && dpkg -i *.deb
rm -rf ~/ncbi-blast-*.rpm ~/ncbi-blast*.deb

echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "----------------------------${w}"
blastx -version | grep Package
echo    "${g}----------------------------"
