#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

#PCRE
#echo "${y}*******************"
#echo 'pcre'
#echo "*******************${w}"

#PCRE_path=/home/$user_name/pcre-8.44/
#PCRE_tar=/home/$user_name/pcre-8.44.tar.gz
#PCRE_url=ftp://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz
#su -c "cd ~/ && wget $PCRE_url" $user_name
#su -c "cd ~/ && tar -zxf $PCRE_tar" $user_name
#su -c "cd $PCRE_path && ./configure --enable-utf8" $user_name
#su -c "cd $PCRE_path && make -j $threads" $user_name
#cd $PCRE_path && sudo make install -j $threads
#rm -rf $PCRE_tar $PCRE_path
#pcre_version=`basename $PCRE_tar | cut -f1,2 -d"."`

#PCRE2
echo "${y}*******************"
echo 'pcre2'
echo "*******************${w}"
PCRE2_url=https://github.com/PhilipHazel/pcre2/releases/download/pcre2-10.39/pcre2-10.39.tar.bz2
PCRE2_path=/home/$user_name/pcre2-10.39/
PCRE2_tar=/home/$user_name/pcre2-10.39.tar.bz2
su -c "cd ~/ && wget $PCRE2_url" $user_name
su -c "cd ~/ && tar -xvf $PCRE2_tar" $user_name
su -c "cd $PCRE2_path && ./configure --enable-utf8" $user_name
su -c "cd $PCRE2_path && make -j $threads" $user_name
cd $PCRE2_path && sudo make install -j $threads
rm -rf $PCRE2_tar $PCRE2_path
pcre2_version=`basename $PCRE2_tar | cut -f1,2 -d"."`


echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "---------------------------${w}"
echo    "$pcre2_version"
echo    "${g}------------------------"
