#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
threads=`nproc`
rm -rf .out.log .err.log
output_log=1
while getopts o name
do
case $name in
o) output_log=$OPTARG;;
esac
done

#install required libs
echo "${g}************************************************"
echo "  ${w}Installing required libraries and R packages${g}"
echo "************************************************${w}"
echo ''
echo -ne '###                                      (8.33%)\r'
sudo apt-fast install -y build-essential fort77 xorg-dev liblzma-dev libblas-dev gfortran gcc-multilib gobjc++ aptitude libcurl4-openssl-dev libbz2-dev libproj-dev > .out.log 2> .err.log
sudo apt-fast install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libproj-dev >> .out.log 2>> .err.log
sudo aptitude install -y libreadline-dev >> .out.log 2>> .err.log
#R update
echo -ne '#####                                   (11.19%)\r'
R -e 'install.packages("BiocManager", repos="http://cran.us.r-project.org")' >> .out.log 2>> .err.log
echo -ne '######                                  (14.05%)\r'
R -e 'update.packages(ask = FALSE, repos="http://cran.us.r-project.org")' >> .out.log 2>> .err.log
echo -ne '#######                                 (16.90%) \r'
R -e 'install.packages("ggalt", dependencies=TRUE, repos="http://cran.us.r-project.org")' >> .out.log 2>> .err.log
echo -ne '########                                (22.62%)\r'
R -e 'install.packages("proj4", repos="http://cran.us.r-project.org")' >> .out.log 2>> .err.log
echo -ne '#########                               (25.48%)\r'
R -e 'BiocManager::install("edgeR")' >> .out.log 2>> .err.log
echo -ne '##########                              (28.33%)\r'
R -e 'BiocManager::install("goseq")' >> .out.log 2>> .err.log
echo -ne '###########                             (31.19%)\r'
R -e 'BiocManager::install("limma")' >> .out.log 2>> .err.log
echo -ne '############                            (34.05%)\r'
R -e 'BiocManager::install("Glimma")' >> .out.log 2>> .err.log
echo -ne '#############                           (36.90%)\r'
R -e 'BiocManager::install("RCurl")' >> .out.log 2>> .err.log
echo -ne '##############                          (39.76%)\r'
R -e 'BiocManager::install("annotate")' >> .out.log 2>> .err.log
echo -ne '###############                         (42.62%)\r'
R -e 'BiocManager::install("GenomicRanges")' >> .out.log 2>> .err.log
echo -ne '################                        (45.48%)\r'
R -e 'BiocManager::install("SummarizedExperiment")' >> .out.log 2>> .err.log
echo -ne '#################                       (48.33%)\r'
R -e 'BiocManager::install("genefilter")' >> .out.log 2>> .err.log
echo -ne '##################                      (51.19%)\r'
R -e 'BiocManager::install("geneplotter")' >> .out.log 2>> .err.log
echo -ne '###################                     (54.05%)\r'
R -e 'BiocManager::install("DESeq2")' >> .out.log 2>> .err.log
echo -ne '####################                    (56.90%)\r'
R -e 'BiocManager::install("ctc")' >> .out.log 2>> .err.log
echo -ne '#####################                   (59.76%)\r'
R -e 'BiocManager::install("Biobase")' >> .out.log 2>> .err.log
echo -ne '######################                  (62.62%)\r'
R -e 'BiocManager::install("gplots")' >> .out.log 2>> .err.log
echo -ne '#######################                 (65.45%)\r'
R -e 'BiocManager::install("ape")' >> .out.log 2>> .err.log
echo -ne '########################                (68.33%)\r'
R -e 'BiocManager::install("qvalue")' >> .out.log 2>> .err.log
echo -ne '#########################               (71.19%)\r'
R -e 'BiocManager::install("fastcluster")' >> .out.log 2>> .err.log
echo -ne '##########################              (74.05%)\r'
R -e 'BiocManager::install("Biobase")' >> .out.log 2>> .err.log
echo -ne '###########################             (76.90%)\r'
R -e 'BiocManager::install("argparse")' >> .out.log 2>> .err.log
echo -ne '############################            (79.76%)\r'
R -e 'BiocManager::install("phytools")' >> .out.log 2>> .err.log
echo -ne '#############################           (82.62%)\r'
R -e 'BiocManager::install("seqLogo")' >> .out.log 2>> .err.log
echo -ne '################################        (85.48%)\r'
R -e 'BiocManager::install("EBSeq")' >> .out.log 2>> .err.log
echo -ne '#################################       (88.33%)\r'
R -e 'BiocManager::install("ggplot2")' >> .out.log 2>> .err.log
echo -ne '##################################      (91.19%)\r'
R -e 'BiocManager::install("grid")' >> .out.log 2>> .err.log
echo -ne '###################################     (94.05%)\r'
R -e 'BiocManager::install("dplyr")' >> .out.log 2>> .err.log
echo -ne '#####################################   (96.90%)\r'
R -e 'BiocManager::install("ggrepel")' >> .out.log 2>> .err.log
echo -ne '######################################  (99.76%)\r'
R -e 'BiocManager::install("BiocManager")' >> .out.log 2>> .err.log
echo -ne '#######################################(100.00%)\r'
R -e 'BiocManager::install("devtools")' >> .out.log 2>> .err.log
echo -ne '#######################################(100.00%)\r'
R -e "BiocManager::install('EnhancedVolcano')" >> .out.log 2>> .err.log
R -e "BiocManager::install('tidyverse')" >> .out.log 2>> .err.log

echo "${g}"
echo    "************************************************"
echo	"${w}Currently installed version:${g}"
echo    "************************************************"
./R-packages_ver

if [ ! -z "$output_log" ]; then
rm -rf .out.log .err.log
else 
echo ''
fi

