#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`
apt-fast install -y libncurses5-dev libncursesw5-dev
#BCFtools
echo "${y}*******************"
echo 'BCFtools'
echo "*******************${w}"

bcf_tools_tar=/home/me/bcftools-1.14.tar.bz2
bcf_tools_path=/home/me/bcftools-1.14/
bcf_tools_url=https://github.com/samtools/bcftools/releases/download/1.14/bcftools-1.14.tar.bz2
su -c "cd ~/ && wget $bcf_tools_url" $user_name
su -c "cd ~/ && tar xjf  $bcf_tools_tar" $user_name
su -c "cd $bcf_tools_path && ./configure" $user_name
cd $bcf_tools_path && make -j $threads prefix=/usr/local/bin install
cd $bcf_tools_path && sudo make install -j $threads
sudo ln -s /usr/local/bin/bin/bcftools /usr/bin/bcftools
rm -rf $bcf_tools_path $bcf_tools_tar

#HTSLIB
echo "${y}*******************"
echo 'Htslib'
echo "*******************${w}"

HTSLIB_tar=/home/me/htslib-1.14.tar.bz2
HTSLIB_path=/home/me/htslib-1.14
HTSLIB_url=https://github.com/samtools/htslib/releases/download/1.14/htslib-1.14.tar.bz2
su -c "cd ~/ && wget $HTSLIB_url" $user_name
su -c "cd ~/ && tar xjf $HTSLIB_tar" $user_name
su -c "cd $HTSLIB_path && ./configure --disable-bz2" $user_name
su -c "cd $HTSLIB_path && make -j $threads" $user_name
cd $HTSLIB_path && sudo make install -j $threads
rm -rf $HTSLIB_path $HTSLIB_tar

#SAMTOOLS
echo "${y}*******************"
echo 'Samtools'
echo "*******************${w}"
samtools_path=/home/me/samtools-1.14
samtools_bz2=/home/me/samtools-1.14.tar.bz2
samtools_url=https://github.com/samtools/samtools/releases/download/1.14/samtools-1.14.tar.bz2
su -c "cd ~/ && wget $samtools_url" $user_name
su -c "cd ~/ && tar xjf $samtools_bz2" $user_name
su -c "cd $samtools_path && ./configure" $user_name
su -c "cd $samtools_path && make -j $threads" $user_name
cd $samtools_path && sudo make install -j $threads
rm -rf $samtools_path $samtools_bz2
samtools_v=`samtools --version | grep samtools`

echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "---------------------------${w}"
bcftools -v | grep bcftools -A 1
echo    "$samtools_v"
echo    "${g}------------------------"


echo "${g}"
echo	"--------------------------------"
echo    "samtools configured successfully"
echo    "--------------------------------"	

