#!/bin/bash
# This script is executed through a primary script

w=$(tput sgr0)
r=$(tput setaf 1)
g=$(tput setaf 2)
y=$(tput setaf 3)

USAGE="USAGE: $0 -u <username>"

if [ "$#" -lt 1 ]; then
    echo -e "$USAGE"
    exit 1
fi

while getopts "u:" option; do
    case "${option}" in
        u) user_name=$OPTARG ;;
    esac
done

if [ -z "$user_name" ]; then
    echo -e "${r}Error: missing argument ${y}-u <username>${w}"
    echo -e "$USAGE"
    exit 1
fi

download_with_retry() {
    local url="$1"; local output="$2"; local label="$3"
    local max_attempts=5; local attempt=1
    while [ "$attempt" -le "$max_attempts" ]; do
        echo "Downloading $label (attempt $attempt of $max_attempts)..."
        su -c "cd ~/ && wget -O '$output' '$url'" "$user_name"
        if [ $? -eq 0 ] && [ -s "$output" ]; then return 0; fi
        rm -f "$output"
        attempt=$((attempt + 1))
    done
    echo "${r}ERROR: Failed to download $label after $max_attempts attempts. Installation aborted.${w}"
    exit 1
}

subread_tar="/home/$user_name/subread-2.1.1-Linux-x86_64.tar.gz"
subread_path="/home/$user_name/subread-2.1.1-Linux-x86_64"
subread_path_bin="subread-2.1.1-Linux-x86_64"
subread_url="https://sitsa.dl.sourceforge.net/project/subread/subread-2.1.1/subread-2.1.1-Linux-x86_64.tar.gz"

download_with_retry "$subread_url" "$subread_tar" "Subread"

su -c "cd ~/ && tar -zxf '$subread_tar'" "$user_name" || exit 1
sudo cp -R "$subread_path" /usr/bin/ || exit 1

sudo ln -fs /usr/bin/$subread_path_bin/bin/exactSNP /usr/bin/exactSNP
sudo ln -fs /usr/bin/$subread_path_bin/bin/featureCounts /usr/bin/featureCounts
sudo ln -fs /usr/bin/$subread_path_bin/bin/subindel /usr/bin/subindel
sudo ln -fs /usr/bin/$subread_path_bin/bin/subjunc /usr/bin/subjunc
sudo ln -fs /usr/bin/$subread_path_bin/bin/sublong /usr/bin/sublong
sudo ln -fs /usr/bin/$subread_path_bin/bin/subread-align /usr/bin/subread-align
sudo ln -fs /usr/bin/$subread_path_bin/bin/subread-buildindex /usr/bin/subread-buildindex

rm -rf "$subread_tar" "$subread_path"

echo "${g}"
echo "----------------------------"
echo "Currently installed version:"
echo "----------------------------${w}"
subread-align -v
echo "${g}----------------------------${w}"
