#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

echo -e "${g}"
echo	"-----------------------------------------------------------------------------------"
echo    "                               Configuring $node_name "
echo    "-----------------------------------------------------------------------------------"
echo	"${g}Node hostname:${w}"
echo	"$node_name"
echo	"${g}User name:${w}"
echo	"$user_name"
echo "${g}-----------------------------------------------------------------------------------"
echo -e "${w}"

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Master home mount
ssh $node_name 'mount master:/home /home'

#Required packages
ssh $node_name "apt --fix-broken install -y"
ssh $node_name 'locale-gen pt_BR.UTF-8'
ssh $node_name "apt-fast install -y gcc libncurses5-dev zlib1g-dev build-essential libxml2-dev build-essential fort77 xorg-dev liblzma-dev libblas-dev gfortran gobjc++ libcurl4-gnutls-dev aptitude libreadline-dev libbz2-dev libssl-dev gedit libcairo2-dev libgtk2.0-dev"
ssh $node_name 'apt-fast install --yes apt-utils perl perl-base git libtbb-dev build-essential libtool -y'
ssh $node_name "sudo aptitude install libreadline-dev -y"
ssh $node_name "apt-fast -y install python-setuptools python-dev build-essential"

#./1-pyhton3-pip-numpy -n $node_name
./2-bzip -n $node_name
./3-bcftools -n $node_name
./4-xz -n $node_name
./5-htslib -n $node_name
./6-cmake -n $node_name
./7-pcre -n $node_name
./8-R -n $node_name
./10-jellyfish -n $node_name
./11-Bowtie2 -n $node_name
./12-samtools -n $node_name
./13-cd-hit -n $node_name
./14-seqtk -n $node_name
./15-ncbi-blast+ -n $node_name
./16-parafly -n $node_name
./17-trinity -n $node_name
#./9-R-packages -n $node_name

echo "${g}"
echo	"------------------------------------------------------------------------------------"
echo    "---------------------- We finhished the node configuration -------------------------"
echo    "------------------------------------------------------------------------------------"
echo    "${p}$node_name${g}"
echo    "------------------------------------------------------------------------------------"
echo    "${p}"
echo	"suport by e-mail to patrick@ufpa.br ${g}"
echo    ""
echo    'Thank you :-D'
echo	" "
echo "
                                 ___        ______    __     __
                                |   |      |	  \  |  \   |  | 
                                |   |      |   D   ) |   \  |  | 
                                |   |      |      /  |    \ |  | 
                                |   |____  |      \  |  |\ \|  | 
                                |        | |   D   ) |  | \    |  
                                |________| |______/  |__|  \___|

                   Laboratório de Biologia Molecular e Neuroecologia  - IFPA"
./sft-ver -n $node_name



