#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | user name | <string>
${w}$USAGE"
exit 1
fi

echo -e "${g}"
echo	"-----------------------------------------------------------------------------------"
echo    "                               Configuring $node_name "
echo    "-----------------------------------------------------------------------------------"
echo	"${g}Node hostname:${w}"
echo	"$node_name"
echo "${g}----------------------------------------------------------------------------------"
echo -e "${w}"

#Set -j option during make process
threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Master home mount
ssh $node_name 'mount master:/home /home'

echo "${y}*******************"
echo 'Python3'
echo "*******************${w}" 
python3_deb_URL=https://master.dl.sourceforge.net/project/rock64-dependencies/Python/python_3.10.2-1_arm64.deb
python3_deb=python_3.10.2-1_arm64.deb
ssh $node_name "cd /node_temp && wget $python3_deb_URL"
ssh $node_name "dpkg -i --force-all /node_temp/$python3_deb"

ssh $node_name 'apt-fast install --yes python-pip python3-pip -y'
ssh $node_name "apt-fast -y install python-setuptools python-dev build-essential"

ssh $node_name "su -c 'pip install numpy' $user_name"
ssh $node_name "su -c 'pip install gffutils' $user_name"
ssh $node_name "su -c 'pip install gffutils' $user_name"
ssh $node_name "pip install --upgrade pip"
# pip3 
ssh $node_name "python3 -m pip install --upgrade pip"
ssh $node_name "python3 -m pip install gffutils"
ssh $node_name "python3 -m pip install numpy"
ssh $node_name "rm -rf /node_temp/"

