#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n: option
do
case "${option}"
in
n) node_name=${OPTARG};;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
echo    "${g}---------------"
echo	"Node hostname:${w}"
echo	"$node_name"
echo "${g}---------------"
echo -e "${w}"
ssh $node_name "mkdir -p /node_temp/"
#Trinity
echo "${y}*******************"
echo 'Trinity'
echo "*******************${w}"
trinity_deb_url=https://master.dl.sourceforge.net/project/rock64-dependencies/Trinity-RNA-Seq/trinityrnaseq_2.11.0-1_arm64.deb
trinity_deb=trinityrnaseq_2.11.0-1_arm64.deb
ssh $node_name "cd /node_temp && wget --show-progress $trinity_deb_url"
ssh $node_name "rm -rf /usr/local/bin/trinityrnaseq*"
ssh $node_name "dpkg -i /node_temp/$trinity_deb"
ssh $node_name "mv /usr/local/bin/trinityrnaseq-* /usr/local/bin/trinityrnaseq-latest"
ssh $node_name "cp -f /usr/bin/ParaFly /usr/local/bin/trinityrnaseq-latest/trinity-plugins/BIN/ParaFly"
ssh $node_name "rm -rf /node_temp/"
