#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

#AUGUSTUS
echo "${y}*******************"
echo 'Augustus'
echo "*******************${w}"
sudo apt-fast install -y zlib1g-dev libgsl-dev libboost-graph-dev libsuitesparse-dev liblpsolve55-dev libsqlite3-dev libgsl-dev libboost-graph-dev libsuitesparse-dev liblpsolve55-dev  libbamtools-dev libboost-all-dev #libmysql++-dev

Augustus_tar=/home/$user_name/3.3.2.tar.gz
Augustus_path=/home/$user_name/Augustus-3.3.2
rm -rf $Augustus_path
su -c "cd ~/ && wget https://github.com/Gaius-Augustus/Augustus/archive/3.3.2.tar.gz" $user_name
su -c "cd ~/ && tar zxf $Augustus_tar" $user_name
su -c "cd $Augustus_path/auxprogs/bam2wig/ && git clone https://github.com/samtools/htslib.git" $user_name
su -c "cd $Augustus_path/auxprogs/bam2wig/htslib && autoheader && autoconf && ./configure && make -j $threads" $user_name
cd $Augustus_path/auxprogs/bam2wig/htslib && sudo make -j $threads install
su -c "cd $Augustus_path/auxprogs/bam2wig/ && git clone https://github.com/samtools/bcftools.git" $user_name
su -c "cd $Augustus_path/auxprogs/bam2wig/bcftools/ && autoheader && autoconf && ./configure && make -j $threads" $user_name
cd $Augustus_path/auxprogs/bam2wig/bcftools/ && sudo make -j $threads install
su -c "cd $Augustus_path/auxprogs/bam2wig/ && git clone https://github.com/samtools/tabix.git" $user_name
su -c "cd $Augustus_path/auxprogs/bam2wig/tabix && make -j $threads" $user_name
su -c "cd $Augustus_path/auxprogs/bam2wig/ && git clone https://github.com/samtools/samtools.git" $user_name
su -c "cd $Augustus_path/auxprogs/bam2wig/samtools && autoheader && autoconf -Wno-syntax && ./configure && make -j $threads" $user_name
cd $Augustus_path/auxprogs/bam2wig/samtools/ && sudo make -j $threads install
su -c "mkdir -p $Augustus_path/bin" $user_name
su -c "cd $Augustus_path/auxprogs/bam2wig/ && export TOOLDIR=/home/$user_name/Augustus-3.3.2/auxprogs/bam2wig/ && cd $Augustus_path/auxprogs/bam2wig/ && make -j $threads" $user_name
su -c "cd $Augustus_path && make -j $threads" $user_name
cd $Augustus_path && sudo make install 
rm -rf $Augustus_tar

echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "----------------------------${w}"
augustus --version
echo    "${g}----------------------------"

