#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

#Jellyfish
echo "${y}*******************"
echo 'Jellyfish'
echo "*******************${w}"
jellyfish_path=/home/$user_name/jellyfish-2.3.0
jellyfish_tar=/home/$user_name/jellyfish-2.3.0.tar.gz
jellyfish_url=https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz
su -c "cd ~/ && wget $jellyfish_url" $user_name
su -c "cd ~/ && tar -zxf $jellyfish_tar" $user_name
su -c "cd $jellyfish_path && ./configure" $user_name
su -c "cd $jellyfish_path && make -j $threads" $user_name
cd $jellyfish_path && sudo make install -j $threads
rm -rf $jellyfish_path $jellyfish_tar
jellyfish_version=`jellyfish --version`
#ssh $user_name@$node_name "echo 'export LD_LIBRARY_PATH=\"/usr/local/lib\"' >> /home/me/.bashrc"
#ssh root@$node_name "echo 'export LD_LIBRARY_PATH=\"/usr/local/lib\"' >> /root/.bashrc"         


echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "---------------------------${w}"
echo    "$jellyfish_version"
echo    "${g}---------------------------"
