#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

#python
echo "${y}*******************"
echo 'python'
echo "*******************${w}"
python_path=/home/$user_name/Python-3.10.2
python_tar=/home/$user_name/Python-3.10.2.tar.xz
python_url=https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tar.xz
su -c "cd ~/ && wget $python_url" $user_name
su -c "cd ~/ && tar -xf $python_tar" $user_name
su -c "cd $python_path && ./configure --enable-optimizations" $user_name
su -c "cd $python_path && make -j $threads" $user_name
cd $python_path && sudo make install -j $threads
python_version=`python3 --version`
ln -fs /usr/local/bin/python3.10 /usr/local/bin/python
su -c 'pip3 install -U setuptools' $user_name
su -c 'pip3 install numpy' $user_name
su -c 'pip3 install --upgrade pip' $user_name
su -c 'pip3 install biopython' $user_name
rm -rf $python_path $python_tar
echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "---------------------------${w}"
echo    "$python_version"
echo    "${g}---------------------------"

