#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

#RSEM opts
echo "${y}*******************"
echo 'RSEM'
echo "*******************${w}"
RSEM_path=/home/$user_name/RSEM-master
RSEM_zip=/home/$user_name/master
RSEM_url=https://codeload.github.com/deweylab/RSEM/zip/master
su -c "cd ~/ && wget $RSEM_url" $user_name
su -c "cd ~/ && unzip -o master -d ~/" $user_name
su -c "cd $RSEM_path && make -j $threads" $user_name
su -c "cd $RSEM_path && make ebseq -j $threads" $user_name
cd $RSEM_path && sudo make install -j $threads
cd $RSEM_path && sudo make ebseq install -j $threads
rm -rf $RSEM_path $RSEM_zip
#	ssh $user_name@$node_name "echo "export PATH=\"$RSEM_path:\$PATH\'" >> /home/me/.bashrc"
#	ssh root@$node_name "echo "export PATH=\"$RSEM_path:\$PATH\'" >> /root/.bashrc"         


echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "----------------------------${w}"
rsem-calculate-expression  --version
echo    "${g}----------------------------"
