#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`

#Xz
echo "${y}*******************"
echo 'XZ'
echo "*******************${w}"
xz_path=/home/me/xz-5.2.5/
xz_tar=/home/me/xz-5.2.5.tar.gz
xz_url=https://sonik.dl.sourceforge.net/project/lzmautils/xz-5.2.5.tar.gz
su -c "cd ~/ && wget $xz_url" $user_name
su -c "cd ~/ && tar -zxf $xz_tar" $user_name
su -c "cd $xz_path && ./configure" $user_name
su -c "cd $xz_path && make -j $threads" $user_name
cd $xz_path && make install -j $threads
ldconfig
rm -rf $xz_path $xz_tar
xz_v=`xz -V | grep xz`


echo "${g}"
echo    "----------------------------"
echo	"Currently installed version:"
echo    "----------------------------${w}"
echo    "$xz_v"
echo    "${g}------------------------"
