#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Blast
echo "${y}*******************"
echo 'Blast'
echo "*******************${w}"
ssh $node_name "apt-fast install alien -y"
blast_url=ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-*.x86_64.rpm
ssh $node_name "cd /node_temp/ && wget $blast_url"
echo "${y}**************************************************************"
echo "Creating a ncbi-blast+ .deb file, this may take a long time..."
echo "**************************************************************${w}"
ssh $node_name "cd /node_temp/ && alien -v -d /node_temp/*.rpm"
echo "${y}************************************************"
echo "instaling ncbi-blast+, this may take a long time"
echo "************************************************${w}"
ssh $node_name "cd /node_temp/ && dpkg -i *.deb"
ssh $node_name "rm -rf /node_temp/ncbi-blast-*.rpm /node_temp/ncbi-blast*.deb"
blast_v=`ssh $node_name blastx -version | grep Package`

ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "----------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------${y}"
echo    "$blast_v"
echo    "${g}---------------------------------------------"
