#!/bin/bash
#Este script é executado atraves de um script primario

w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi


#Set -j option during make process
	threads=`ssh $node_name nproc`
#create temp dir
ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"

#Master home mount
ssh $node_name 'mount master:/home /home'

#bzip
echo "${y}*******************"
echo 'bzip2'
echo "*******************${w}"
bzip2_tar=/node_temp/master.zip
bzip2_path=/node_temp/bzip2-1.0.6-master
bzip_URL=https://github.com/enthought/bzip2-1.0.6/archive/master.zip
ssh $node_name "su -c 'cd /node_temp/ &&  wget $bzip_URL' $user_name"
ssh $node_name "su -c 'cd /node_temp/ && unzip -o $bzip2_tar -d /node_temp/' $user_name"
ssh $node_name "su -c 'cd $bzip2_path && make -j $threads' $user_name"
ssh $node_name "cd $bzip2_path && make install -j $threads"
echo "${g}"
echo    "---------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------${y}"
basename $bzip2_path | awk -F'[_]' '{print $1}'
ssh $node_name "rm -rf $bzip2_path $bzip2_tar"
ssh $node_name 'rm -rf /node_temp/'
echo    "${g}---------------------------------"
