#!/bin/bash
#Este script é executado atraves de um script primario

w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
p=$(tput setaf 5) 
USAGE="USAGE: $0 -n <nodename> -u <username>"

if [ "$#" -lt "2" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts n:u: option
do
case "${option}"
in
n) node_name=${OPTARG};;
u) user_name=$OPTARG;;
esac
done

if [ "$node_name" = "" ]; then
"${g}Error, missing arguments:${y} -n | Node hostname | <string>
${w}$USAGE"
exit 1
fi
if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi

echo -e "${g}"
echo	"-----------------------------------------------------------------------------------"
echo    "------------------------------ Configuring Trinity --------------------------------"
echo    "-----------------------------------------------------------------------------------"
echo	"${g}Node hostname:${w}"
echo	"$node_name"
echo	"${g}User name:${w}"
echo	"$user_name"
echo "${g}----------------------------------------------------------------------------------"
echo -e "${w}"
threads=`ssh $node_name nproc`

ssh $node_name 'rm -rf /node_temp/'
ssh $node_name 'mkdir -p /node_temp/'
ssh $node_name "chown -R $user_name:$user_name /node_temp/"
ssh $node_name 'mount master:/home /home'

#HMMER
echo "${y}*******************"
echo 'HMMER'
echo "*******************${w}"
hmmer_tar=/node_temp/hmmer.tar.gz
hmmer_path=/node_temp/hmmer-3.3.2
hmmer_url=http://eddylab.org/software/hmmer/hmmer.tar.gz
ssh $node_name "su -c 'cd /node_temp && wget $hmmer_url' $user_name"
ssh $node_name "su -c 'cd /node_temp && tar zxf $hmmer_tar' $user_name"
ssh $node_name "su -c 'cd $hmmer_path && ./configure' $user_name"
ssh $node_name "su -c 'cd $hmmer_path && make -j $threads' $user_name"
ssh $node_name "cd $hmmer_path && sudo make install -j $threads"
#ssh $node_name "rm -rf $hmmer_tar $hmmer_path"
hmmer_v=`ssh $node_name hmmscan -h | grep HMMER`

#ssh $node_name 'rm -rf /node_temp/'
echo "${g}"
echo    "---------------------------------------------------"
echo	"Hostname=${w}$node_name                      " 
echo	"${g}Currently installed versions:"
echo    "---------------------------------------------------${y}"
echo    "$hmmer_v"
echo    "${g}---------------------------------------------"
