#!/bin/bash
#Este script é executado atraves de um script primario
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
USAGE="USAGE: $0 -u <username>"
if [ "$#" -lt "1" ] 
then 
    echo -e $USAGE;
exit 1    
else 
    var1=$2;
fi

while getopts u: option
do
case "${option}"
in
u) user_name=$OPTARG;;
esac
done

if [ "$user_name" = "" ]; then
"${g}Error, missing arguments:${y} -u | User name | <string>
${w}$USAGE"
exit 1
fi
threads=`nproc`
#bzip
echo "${y}*******************"
echo 'Bzip2'
echo "*******************${w}"
bzip2_tar=/home/me/bzip2-1.0.6.tar.gz
bzip2_path=/home/me/bzip2-1.0.6
bzip2_url=https://sonik.dl.sourceforge.net/project/bzip2/bzip2-1.0.6.tar.gz
su -c "cd ~/ &&  wget $bzip2_url" $user_name
su -c "cd ~/ && tar -zxf $bzip2_tar" $user_name
su -c "cd $bzip2_path && make -j $threads" $user_name
cd $bzip2_path && make install -j $threads
rm -rf $bzip2_path $bzip2_tar
#bzip2_ver=`bzip2 -V`

echo "${g}"
echo    "-----------------------------"
echo	"Currently installed versions:"
echo    "-----------------------------${w}"
bzip2 -V
echo    "${g}-----------------------------"

